hyperparameters:
    n_steps: 4096
    batch_size: 1024
    gae_lambda: 0.95
    gamma: 0.99
    n_epochs: 10
    ent_coef: 0.0
    learning_rate: 2.5e-4
    clip_range: 0.2
training_parameters:
    name: PPO
    eval: True
    eval_freq: 100000
    eval_render: False
    show_window: True
    speedup: 8
    eval_speedup: 8
    iterations: 10000000
    export: True
    save_freq: 500000
    save_path: save/models
    load_path: save/models/best_model
    deterministic: False
    verbose: 0
    log: True
    